### ISSUE TITLE
AssertionError during cancel()

### ISSUE THREAD

**Issue by sallner** [zopefoundation/zope.server#21]
I encountered an `AssertionError` during call of `AbstractTask.service.cancel()`, see the following traceback. 

```
Exception during task module=zope.server.taskthreads process=<my-service>
Traceback (most recent call last):
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/taskthreads.py", line 48, in handlerThread
task.service()
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/serverchannelbase.py", line 205, in service
task.service()
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/task.py", line 58, in service
self.cancel()
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/task.py", line 65, in cancel
self.channel.close_when_done()
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/dualmodechannel.py", line 198, in close_when_done
while self._flush_some():
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/dualmodechannel.py", line 190, in _flush_some
num_sent = self.send(chunk)
File "/usr/lib/python2.7/asyncore.py", line 380, in send
self.handle_close()
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/dualmodechannel.py", line 61, in handle_close
self.close()
File ".../eggs/zope.server-4.0.2-py2.7.egg/zope/server/dualmodechannel.py", line 211, in close
assert self.async_mode
AssertionError
```

Do you have any ideas, why we end up here? Should `cancel_when_done` not take care of this?
After this error, the server seems to recover from it.

**Comment by mgedmin** [comment]
I've seen this error before, but it happened rarely enough that I never spent much effort tracking it down:
- https://mail.zope.org/pipermail/zope-dev/2011-December/043889.html
